export type Product = {
  id: string;
  slug?: string;
  name: string;
  summary?: string;
  description: string;
  tag?: string;
  gender?: string;
  highlights?: string[];
  price: number;
  salePrice?: number;
  onSale?: boolean;
  isBestSeller?: boolean;
  isNewArrival?: boolean;
  inStock?: boolean;
  image: string;
  images?: string[];
  category: string;
  stock: number;
  sizes?: string[];
  colors?: string[];
  brand?: string;
  collection?: string;
  createdAt: string;
};
