// Datos de productos de ejemplo con las nuevas propiedades
export const sampleProducts = [
  {
    id: '1',
    name: 'Hoodie Andes',
    description: 'Felpa pesada, capucha amplia y ajuste premium.',
    price: 189000,
    salePrice: 149000,
    onSale: true,
    isBestSeller: true,
    isNewArrival: false,
    inStock: true,
    stock: 15,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800'],
    category: 'Hoodies',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Negro', 'Gris'],
    brand: 'Street World',
    createdAt: '2026-02-01T00:00:00Z'
  },
  {
    id: '2',
    name: 'Cargo Distrito',
    description: 'Cargo de ajuste relajado y bolsillos utilitarios.',
    price: 159000,
    onSale: false,
    isBestSeller: true,
    isNewArrival: false,
    inStock: true,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    category: 'Pantalones',
    sizes: ['28', '30', '32', '34'],
    colors: ['Negro', 'Verde Militar', 'Beige'],
    brand: 'Street World',
    createdAt: '2026-01-15T00:00:00Z'
  },
  {
    id: '3',
    name: 'Bucket Origen',
    description: 'Bucket ligero con bordado interno Street World.',
    price: 89000,
    salePrice: 69000,
    onSale: true,
    isBestSeller: false,
    isNewArrival: false,
    inStock: true,
    stock: 5,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800',
    category: 'Accesorios',
    sizes: ['Única'],
    colors: ['Negro', 'Beige'],
    brand: 'Street World',
    createdAt: '2026-01-20T00:00:00Z'
  },
  {
    id: '4',
    name: 'Tee Avenida',
    description: 'Camiseta oversize con cuello alto y caída amplia.',
    price: 79000,
    onSale: false,
    isBestSeller: true,
    isNewArrival: true,
    inStock: true,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
    category: 'Camisetas',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Negro', 'Blanco', 'Gris'],
    brand: 'Street World',
    createdAt: '2026-02-25T00:00:00Z'
  },
  {
    id: '5',
    name: 'Chaqueta Barrio',
    description: 'Chaqueta ligera con forro y detalles reflectivos.',
    price: 249000,
    salePrice: 199000,
    onSale: true,
    isBestSeller: false,
    isNewArrival: true,
    inStock: true,
    stock: 10,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
    category: 'Chaquetas',
    sizes: ['M', 'L', 'XL'],
    colors: ['Negro', 'Gris Oscuro'],
    brand: 'Street World',
    createdAt: '2026-02-20T00:00:00Z'
  },
  {
    id: '6',
    name: 'Gorra Summit',
    description: 'Gorra estructurada con visera curva.',
    price: 59000,
    onSale: false,
    isBestSeller: false,
    isNewArrival: true,
    inStock: true,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800',
    category: 'Accesorios',
    sizes: ['Única'],
    colors: ['Negro', 'Blanco', 'Rojo'],
    brand: 'Street World',
    createdAt: '2026-02-26T00:00:00Z'
  },
  {
    id: '7',
    name: 'Jogger Urbano',
    description: 'Pantalón jogger con cintura elástica y bolsillos laterales.',
    price: 139000,
    salePrice: 99000,
    onSale: true,
    isBestSeller: true,
    isNewArrival: false,
    inStock: true,
    stock: 18,
    image: 'https://images.unsplash.com/photo-1608489969867-8d3e6da84da9?w=800',
    category: 'Pantalones',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Negro', 'Gris', 'Azul Marino'],
    brand: 'Street World',
    createdAt: '2026-01-10T00:00:00Z'
  },
  {
    id: '8',
    name: 'Bomber Nocturno',
    description: 'Chaqueta bomber con forro acolchado y cierre metálico.',
    price: 279000,
    onSale: false,
    isBestSeller: true,
    isNewArrival: true,
    inStock: true,
    stock: 8,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800',
    category: 'Chaquetas',
    sizes: ['M', 'L', 'XL'],
    colors: ['Negro', 'Verde Oliva'],
    brand: 'Street World',
    createdAt: '2026-02-24T00:00:00Z'
  }
];
